In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
%matplotlib inline

### iris dataset from sklearn.datasets

In [3]:
#object of dataset
iris=load_iris()

In [4]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
df=pd.DataFrame(iris.data,columns=iris.feature_names)

In [8]:
df['target']=iris.target

In [9]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [10]:
# mapping target name with the dataframe on the basis of target column
df['target_name']=list(map(lambda x:iris.target_names[x],df['target']))

In [11]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,target_name
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa

### Dataset splitting

In [71]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']],df['target_name'])

In [72]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)

In [73]:
for train_index,test_index in kf.split(df[['sepal length (cm)','sepal width (cm)','petal length (cm)'\
                                           ,'petal width (cm)']],df['target_name']):
    
    print(train_index,test_index)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103
 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 147 148 149] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49 100 101 102 103
 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 147 148 149] [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

In [36]:
#fuction which return score of different function on different test set
# x_train,x_test,y_train,y_test
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
def get_score(model):
    kf=KFold(n_splits=5)
    for train_index,test_index in kf.split(df[['sepal length (cm)','sepal width (cm)','petal length (cm)'\
                                           ,'petal width (cm)']],df['target_name']):
        x_train=df.iloc[train_index,0:4]
        x_test=df.iloc[test_index,0:4]
        y_train=df.iloc[train_index,5]
        y_test=df.iloc[test_index,5]
        # print(y_test)
        model.fit(x_train,y_train)
        y_pred=model.predict(x_test)
        #print(y_train)
        print(model.score(x_test,y_test))
        # print(" {} ".format(model.score(x_test,y_test)))

In [37]:
from sklearn import linear_model
model=linear_model.LogisticRegression()
get_score(model)

1.0
1.0
0.8666666666666667
0.9333333333333333
0.8333333333333334

C:\Users\welcome\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\welcome\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\welcome\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
17                 5.1               3.5                1.4               0.3
147                6.5               3.0                5.2               2.0
51                 6.4               3.2                4.5               1.5
137                6.4               3.1                5.5               1.8
126                6.2               2.8                4.8               1.8
148                6.2               3.4                5.4               2.3
95                 5.7               3.0                4.2               1.2
105                7.6               3.0                6.6               2.1
9                  4.9               3.1                1.5               0.1
49                 5.0               3.3                1.4               0.2
93                 5.0               2.3                3.3               1.0
36                 5.5               3.5                1.3               0.2
128                6.4               2.8                5.6               2.1
97                 6.2               2.9                4.3               1.3
90                 5.5               2.6                4.4               1.2
2                  4.7               3.2                1.3               0.2
18                 5.7               3.8                1.7               0.3
103                6.3               2.9                5.6               1.8
32                 5.2               4.1                1.5               0.1
0                  5.1               3.5                1.4               0.2
79                 5.7               2.6                3.5               1.0
98                 5.1               2.5                3.0               1.1
39                 5.1               3.4                1.5               0.2
26                 5.0               3.4                1.6               0.4
63                 6.1               2.9                4.7               1.4
80                 5.5               2.4                3.8               1.1
61                 5.9               3.0                4.2               1.5
78                 6.0               2.9                4.5               1.5
3                  4.6               3.1                1.5               0.2
64                 5.6               2.9                3.6               1.3
96                 5.7               2.9                4.2               1.3
60                 5.0               2.0                3.5               1.0
144                6.7               3.3                5.7               2.5
108                6.7               2.5                5.8               1.8
82                 5.8               2.7                3.9               1.2
67                 5.8               2.7                4.1               1.0
48                 5.3               3.7                1.5               0.2
12                 4.8               3.0                1.4               0.1